parameters:
    ruch_jow_ajax_auth.auth_handler.class: RuchJow\AjaxAuthBundle\Handler\AuthenticationHandler
    ruch_jow_ajax_auth.auth_exception_listener.class: RuchJow\AjaxAuthBundle\Listener\AjaxAuthenticationListener
services:
    ruch_jow_ajax_auth.auth_handler:
        class: %ruch_jow_ajax_auth.auth_handler.class%
        arguments:
            - "@security.http_utils"
            - "/"
            - "/login"
            - "/"

    ruch_jow_ajax_auth.ajax_authentication_listener:
        class: %ruch_jow_ajax_auth.auth_exception_listener.class%
        arguments: [ "@security.context" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }